services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app-${APP_ENV}
    restart: always
    volumes:
      - laravel_app_data-${APP_ENV}:/var/www
    networks:
      - laravel_${APP_ENV}_environment

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - laravel_app_data-${APP_ENV}:/var/www:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - laravel_dev_environment
      - laravel_prod_environment

 certbot:
    image: certbot/certbot:latest
    container_name: laravel_certbot
    restart: unless-stopped
    volumes:
      - ${CERTBOT_WWW_VOLUME:-certbot-www}:/var/www/certbot
      - ${CERTBOT_CERTS_VOLUME:-certbot-certs}:/etc/letsencrypt
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done;'"


  redis:
    image: redis:7-alpine
    container_name: laravel_redis-${APP_ENV}
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    networks:
      - laravel_${APP_ENV}_environment

  db:
    image: postgres:15-alpine
    container_name: laravel_db-${APP_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel_${APP_ENV}_environment

volumes:
  laravel_app_data:
  pg_data:
  redis_data:
  certbot_www:
  certbot_certs:

networks:
  laravel_dev_environment:
    external: true
#  laravel_prod_environment:
#    external: true
