services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app-${APP_ENV}
    restart: always
    volumes:
      - laravel_app_data:/var/www
    networks:
      - proxy


  redis:
    image: redis:7-alpine
    container_name: laravel_redis-${APP_ENV}
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    networks:
      - proxy

  db:
    image: postgres:15-alpine
    container_name: laravel_db-${APP_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - proxy
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - laravel_app_data:/var/www:ro
      - /var/www/certbot/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`dev.feuerwehr-quierschied.org`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
volumes:
  laravel_app_data:
  pg_data:
  redis_data:


networks:
  laravel_dev_environment:
  proxy:
    external: true
