services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app-${APP_ENV}
    restart: always
    volumes:
      - laravel_app_data:/var/www
    networks:
      - laravel_${APP_ENV}_environment
      - nginx_network


  redis:
    image: redis:7-alpine
    container_name: laravel_redis-${APP_ENV}
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    networks:
      - laravel_${APP_ENV}_environment

  db:
    image: postgres:15-alpine
    container_name: laravel_db-${APP_ENV}
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - laravel_${APP_ENV}_environment

volumes:
  laravel_app_data:
    external: true
  pg_data:
  redis_data:


networks:
  laravel_dev_environment:
  nginx_network:
    external: true
